### ISSUE TITLE
Different disruptor usage with different nodes in a scenario

### ISSUE THREAD

**Issue by gvinet** [k0retux/fuddly#29]
Hello,

I have created a scenario with 3 nodes linked with steps: A -> B -> C

I want to : 
* use a disruptor tTYPE on path path_b of the node B, 
* and then I want to use another disruptor tTYPE on path_c of the node C.

However, when I execute the scenario and go to node C, it uses the first disruptor with path set to path_b instead of creating another one with the correct path.

How can use two different disruptor instantiation?

Thank

**Comment by gvinet** [comment]
It seems I need to use the notation tTYPE, tTYPE#1. It leads to clone the disruptor, and I obtain the expected behavior.

plumbing.py:
```python
self.check_clone_re = re.compile('(.*)#(\w{1,20})')
[...]
parsed = self.check_clone_re.match(dmaker_type)
                if parsed is not None:
[...]
ok, cloned_dmaker_name = clone_gen_dmaker(cloned_dmaker_type, new_dmaker_type=dmaker_type, dmaker_name=provided_dmaker_name)
```

**Comment by k0retux** [comment]
Hello, (sorry for the late answer)

Note that it is also indicated in the documentation there:
http://fuddly.readthedocs.io/en/develop/tutorial/#resetting-cloning-disruptors

Regards
