### ISSUE TITLE
EvolutionaryScenariosFactory example

### ISSUE THREAD

**Issue by Matheus-Garbelini** [k0retux/fuddly#30]
Hello, I couldn't find a example to use EvolutionaryScenariosFactory.
Can I use the Evolutionary api direct by code instead of using the shell?

**Comment by k0retux** [comment]
Hello,

The Evolutionary API can be used either through the fuddly shell or directly through any python interpreter, like any other parts of the framework. You need at least to instantiate the plumbing, then, to run the project you want, before doing whatever you like (look at FmkShell methods for inspiration):

fmk = FmkPlumbing()
fmk.start()
fmk.run_project(name=..., ...)

Note that Evolutionary part of the framework are going to be updated soon (at least moving the specification at project level). Anyway I've just fixed a bug that prevented the Evolutionary system to work, and updated the documentation (refer to section 7.2) for more details in the setup.
Pull the develop branch for now.

**Comment by Matheus-Garbelini** [comment]
@k0retux Thanks, I tried to use the API without plumbing and it produced some bugs. I imagine that could be the bugs you fixed. Meanwhile I'm implementing 802.11 specification.

**Comment by k0retux** [comment]
Hi,

Good to know that you are implementing 802.11.
Regarding the usage of fuddly features, note that the plumbing
(FmkPlumbing) is needed for many aspects (sequencing, feedback
retrieval/distribution, registration in fmkDB, scenario processing, and so
on...). You can see it as a runtime.
However, FmkShell is fully optional.

Have a good day,

Eric

Le mar. 5 mars 2019 à 16:39, Matheus Eduardo <notifications@github.com> a
écrit :
