### ISSUE TITLE
New conditions support

### ISSUE THREAD

**Issue by Matheus-Garbelini** [k0retux/fuddly#31]
Hello, I have a piece of a field that is written that way:
```Python
 {
                    'name': 'HeaderFlags',
                    'contents': lambda x: Node('General', value_type= \
                        String(min_sz=4, max_sz=uint16le_to_int(x) - 4, determinist=False)),
                    'node_args': 'HeaderLength',
                    'exists_if': (IntMoreOrEqualThanCondition(9), 'HeaderLength')
}
```
I couldn't find a way to include a field if a length value is greater than a certain number, so I had to write a new class *IntMoreOrEqualThanCondition*. But I don't think this is good enough, maybe a more general solution could be used, such as using a lambda condition, so users can decide what to compere the value to?

Other difficulties I have:
* For packets that don't inform sizes but you can infer the next fields based on the packer size left. This is specially true for wifi tagged fields packet, which don't have a field telling how many tags there are. You can only now if you check if there's more bytes left. Do you have a tip how to read the bytes left from the current node? I found difficult to receive node context inside the condition class.
* Is it possible that the use of lambdas doesn't include a new node? I get a new child node which is not at the same level of the parent node, polluting a little the .show()
* I can't use the extended bitfield. I'm trying to use 2 bitfields without padding so they can by seen as just one byte, but it seems the framework doesn't have a complete support for that besides the `extend` function.

Thank you very much

**Comment by k0retux** [comment]
Hello,

Currently, there are 3 subclasses of NodeCondition that check inclusion (or not) to a set of values. There are clearly other use cases (like yours) that could benefit from new NodeCondition. Adding a GT and a LT NodeCondition when an ordered set is used (like the Integers) should provide enough flexibility (in conjunction with the AND and OR operators used by "exists_if/and" and "exists_if/or"). For other set dealing with Strings for instance, we can imagine other kinds of condition (starts_with, etc.) that could justify to add a generic NodeCondition constructor based on a function as you mention.
--> I add that to my TODO list :) (could be part of 0.27.2)

Regarding, your other difficulties:
- If your use case is to absorb/dissect existing packets, and that the size is the main constraint for performing the absorption, then you could describe the different shapes like you see in the documentation 3.1.2 (keyword 'weight'), and the absorption algorithm should do the good matching for you (given that you provide an AbsCsts(size=True, ...) ). Regarding node generation, the different shapes will be chosen either randomly or deterministicly depending on the conf of the node including these shapes. (*)
- When you use a generator-based node, you always have an extra layer that can be transparent for some actions (but for others you need to have visibility on that extra layer). Currently, Node.show() displays that extra layer to you. I could indeed add an option to ignore the display of that extra layer, which could be useless for some use cases. (--> TODO)
- For using BitField that does not have a byte boundary you need to customize the parent node  ('custo_set': MH.Custo.NTerm.CollapsePadding) like it is done in the SMS data model.

(*) For other use cases, if you need introspection on the node graph from any node, then it is through the Env() object shared between all of them. You can benefit from that through generator nodes. For more details on how it can be used (indirectly) you can refer to the source code of the generic generator OFFSET (framework/dmhelpers/generic.py), that allows to retrieve the offset of any node.

I hope to have answered to your expectations.
