### ISSUE TITLE
Move jsonschema to a Dev Dependency (If Applicable)

### ISSUE THREAD

**Issue by jkylekelly** [k0retux/fuddly#56]
Hi there! 👋

I'm a researcher exploring unused software dependencies in Python projects, and I noticed that jsonschema doesn't appear to be directly used in the codebase. If it's being utilized via the CLI for testing or some other non-production use case, it might make sense to move it to a dev dependency instead of keeping it as a runtime dependency.

I realize this might be a bit of a nitpick (and feel free to tell me if you disagree! 😊), but I'm working on a tool to identify such cases.  Identifying edge cases where the tool is failing would be helpful! Thanks for your time - and I appreciate the readme dependency notes!

**Comment by k0retux** [comment]
Hey, sorry for my late answer. It is an obsolete dependency and I removed it.
